### ISSUE TITLE
Request for Access to Accident Driving Recording Data

### ISSUE THREAD

**Issue by ChenDolph7in** [acav2023/ACAV-SourceCode#1]
I hope this message finds you well.  I am currently working on a project related to autonomous vehicle safety analysis. I recently came across your paper and found your research incredibly insightful. I am particularly interested in the accident driving recordings you mentioned in your paper.  
Specifically, I am looking to access the driving recordings generated through the AVUnit framework, which you used to test various accident scenarios.Would it be possible for you to share the accident driving recordings dataset mentioned in your paper?
Thank you very much for considering my request.
Best regards.

**Comment by tikrgi620** [comment]
Regarding your request for the accident driving recordings, you can generate similar driving recordings by using the AVUnit framework yourself. For detailed instructions on how to use AVUnit and any questions regarding its licensing and usage, I recommend contacting the authors of the AVUnit framework directly.
